all:

	g++ -std=c++11 BadGuy.cpp Block.cpp BoundingBox3d.cpp Camera.cpp Character.cpp Coin.cpp Color.cpp Game.cpp glbmp.c Heightmap.cpp Level.cpp Light.cpp main.cpp Material.cpp MD2Model.cpp Plane3d.cpp Player.cpp SkyBox.cpp Sound.cpp TextureLoader.cpp Vector3.cpp -lopenal -lGL -lGLU -lglut -lalut
